ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.1
    two_d_mode: true
    publish_tf: true

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    # ==========================================
    # 1. CONFIGURACIÓN DE ODOMETRÍA (Ruedas)
    # ==========================================
    odom0: /diff_drive_controller/odom
    # [X, Y, Z,
    #  Roll, Pitch, Yaw,
    #  Vx, Vy, Vz,
    #  Vroll, Vpitch, Vyaw,
    #  Ax, Ay, Az]
    odom0_config: [false, false, false,
                   false, false, false,
                   true,  true,  false,
                   false, false, true,
                   false, false, false]
    odom0_differential: false

    # ==========================================
    # 2. CONFIGURACIÓN DE LA IMU
    # ==========================================
    imu0: /imu
    imu0_config: [false, false, false,
                  false, false, true,
                  false, false, false,
                  false, false, true,
                  true,  true,  false]
    imu0_differential: false
    imu0_remove_gravitational_acceleration: true
