mission_waypoints:
  - name: "zona_triaje"
    position:
      x: 1.69
      y: 0.86
    orientation:
      theta: 0.0
  - name: "pasillo_principal"
    position:
      x: -0.54
      y: 2.98
    orientation:
      theta: -1.57
  - name: "punto_hospital"
    position:
      x: 2.22
      y: 4.66
    orientation:
      theta: 3.14
